### ISSUE TITLE
为啥不同的设备上有些会解码失败，Log如下，是不是因为不同ROM底层的FFmpeg版本等等等差异，可否解决一下

### ISSUE THREAD

**Issue by spianmo** [lesa1127/AndroidScreenShare#1]
`2019-09-05 11:53:14.659 4009-4258/com.trap.terminal D/AudioTrack: set(sessionID=0)
2019-09-05 11:53:14.659 4009-4258/com.trap.terminal D/AudioTrack: set(): streamType -1, sampleRate 44100, format 0x1, channelMask 0x1, frameCount 3536, flags #0, notificationFrames 0, sessionId 0, transferType 3, uid -1, pid -1
2019-09-05 11:53:14.661 4009-4261/com.trap.terminal I/OMXClient: IOmx service obtained
2019-09-05 11:53:14.667 4009-4259/com.trap.terminal D/SurfaceUtils: connecting to surface 0x7aabec0010, reason connectToSurface
2019-09-05 11:53:14.667 4009-4259/com.trap.terminal I/MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 4105218
2019-09-05 11:53:14.667 4009-4259/com.trap.terminal D/SurfaceUtils: disconnecting from surface 0x7aabec0010, reason connectToSurface(reconnect)
2019-09-05 11:53:14.667 4009-4259/com.trap.terminal D/SurfaceUtils: connecting to surface 0x7aabec0010, reason connectToSurface(reconnect)
2019-09-05 11:53:14.668 4009-4261/com.trap.terminal I/ExtendedACodec: setupVideoDecoder()
2019-09-05 11:53:14.668 4009-4261/com.trap.terminal I/ExtendedACodec: Decoder will be in frame by frame mode
2019-09-05 11:53:14.707 4009-4261/com.trap.terminal D/SurfaceUtils: set up nativeWindow 0x7aabec0010 for 1080x2340, color 0x7fa30c06, rotation 0, usage 0x20002900
2019-09-05 11:53:14.720 4009-4258/com.trap.terminal W/AudioTrack: Use of stream types is deprecated for operations other than volume control
2019-09-05 11:53:14.720 4009-4258/com.trap.terminal W/AudioTrack: See the documentation of AudioTrack() for what to use instead with android.media.AudioAttributes to qualify your playback use case
2019-09-05 11:53:14.726 4009-4265/com.trap.terminal I/OMXClient: IOmx service obtained
2019-09-05 11:53:14.727 4009-4265/com.trap.terminal W/ExtendedACodec: Failed to get extension for extradata parameter
2019-09-05 11:53:15.616 4009-4238/com.trap.terminal W/AudioTrack: releaseBuffer() track 0x7abee61c00 disabled due to previous underrun, restarting
2019-09-05 11:53:15.619 4009-4235/com.trap.terminal E/Media: onFrame start
2019-09-05 11:53:15.619 4009-4235/com.trap.terminal E/Media: onFrame Thread:1991
2019-09-05 11:53:15.619 4009-4235/com.trap.terminal E/Media: onFrame index:0
2019-09-05 11:53:15.619 4009-4244/com.trap.terminal E/ACodec: dequeueBuffer failed: NO_INIT(-19).
2019-09-05 11:53:15.620 4009-4235/com.trap.terminal E/Media: onFrame end
2019-09-05 11:53:15.620 4009-4235/com.trap.terminal E/Media: onFrame start
2019-09-05 11:53:15.620 4009-4235/com.trap.terminal E/Media: onFrame Thread:1991
2019-09-05 11:53:15.620 4009-4235/com.trap.terminal E/Media: onFrame index:1
2019-09-05 11:53:15.620 4009-4244/com.trap.terminal E/ACodec: dequeueBuffer failed: NO_INIT(-19).
2019-09-05 11:53:15.621 4009-4235/com.trap.terminal E/Media: onFrame end
2019-09-05 11:53:15.621 4009-4235/com.trap.terminal E/Media: onFrame start
2019-09-05 11:53:15.621 4009-4235/com.trap.terminal E/Media: onFrame Thread:1991
2019-09-05 11:53:15.621 4009-4235/com.trap.terminal E/Media: onFrame index:2
2019-09-05 11:53:15.621 4009-4244/com.trap.terminal E/ACodec: dequeueBuffer failed: NO_INIT(-19).
2019-09-05 11:53:15.621 4009-4235/com.trap.terminal E/Media: onFrame end
2019-09-05 11:53:15.621 4009-4235/com.trap.terminal E/Media: onFrame start
2019-09-05 11:53:15.621 4009-4235/com.trap.terminal E/Media: onFrame Thread:1991
2019-09-05 11:53:15.621 4009-4235/com.trap.terminal E/Media: onFrame index:3
2019-09-05 11:53:15.622 4009-4244/com.trap.terminal E/ACodec: dequeueBuffer failed: NO_INIT(-19).
2019-09-05 11:53:15.622 4009-4235/com.trap.terminal E/Media: onFrame end
2019-09-05 11:53:15.622 4009-4235/com.trap.terminal E/Media: onFrame start
2019-09-05 11:53:15.622 4009-4235/com.trap.terminal E/Media: onFrame Thread:1991
2019-09-05 11:53:15.622 4009-4235/com.trap.terminal E/Media: onFrame index:4
2019-09-05 11:53:15.622 4009-4244/com.trap.terminal E/ACodec: dequeueBuffer failed: NO_INIT(-19).
2019-09-05 11:53:15.622 4009-4235/com.trap.terminal E/Media: onFrame end
2019-09-05 11:53:15.623 4009-4235/com.trap.terminal E/Media: onFrame start
2019-09-05 11:53:15.623 4009-4235/com.trap.terminal E/Media: onFrame Thread:1991
2019-09-05 11:53:15.623 4009-4235/com.trap.terminal E/Media: onFrame index:5
2019-09-05 11:53:15.623 4009-4244/com.trap.terminal E/ACodec: dequeueBuffer failed: NO_INIT(-19).
2019-09-05 11:53:15.623 4009-4235/com.trap.terminal E/Media: onFrame end
2019-09-05 11:53:15.623 4009-4235/com.trap.terminal E/Media: onFrame start
2019-09-05 11:53:15.623 4009-4235/com.trap.terminal E/Media: onFrame Thread:1991
2019-09-05 11:53:15.626 4009-4244/com.trap.terminal W/SurfaceUtils: failed to get consumer usage bits. ignoring
2019-09-05 11:53:15.626 4009-4244/com.trap.terminal D/SurfaceUtils: set up nativeWindow 0x7aabb5d010 for 1088x2352, color 0x7fa30c06, rotation 0, usage 0x20002900
2019-09-05 11:53:15.626 4009-4244/com.trap.terminal E/ACodec: NATIVE_WINDOW_MIN_UNDEQUEUED_BUFFERS query failed: No such device (19)
2019-09-05 11:53:15.626 4009-4244/com.trap.terminal E/ACodec: Failed to allocate output port buffers after port reconfiguration: (-19)
2019-09-05 11:53:15.626 4009-4244/com.trap.terminal E/ACodec: signalError(omxError 0x80001001, internalError -19)
2019-09-05 11:53:15.626 4009-4244/com.trap.terminal E/ACodec: Error occurred while disabling the output port
2019-09-05 11:53:15.626 4009-4242/com.trap.terminal E/MediaCodec: Codec reported err 0xffffffed, actionCode 0, while in state 6
2019-09-05 11:53:15.627 4009-4235/com.trap.terminal E/Media: onFrame faile
2019-09-05 11:53:15.627 4009-4235/com.trap.terminal W/System.err: java.lang.IllegalStateException
2019-09-05 11:53:15.627 4009-4235/com.trap.terminal W/System.err:     at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
2019-09-05 11:53:15.627 4009-4235/com.trap.terminal W/System.err:     at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2635)
2019-09-05 11:53:15.627 4009-4235/com.trap.terminal W/System.err:     at com.trap.terminal.media.Decoder.onFrame(Decoder.java:52)
2019-09-05 11:53:15.627 4009-4235/com.trap.terminal W/System.err:     at com.trap.terminal.VideoPlayThread.run(VideoPlayThread.java:46)
2019-09-05 11:53:15.627 4009-4235/com.trap.terminal E/Media: onFrame start
2019-09-05 11:53:15.628 4009-4235/com.trap.terminal E/Media: onFrame Thread:1991
2019-09-05 11:53:15.628 4009-4242/com.trap.terminal D/SurfaceUtils: disconnecting from surface 0x7aabb5d010, reason disconnectFromSurface
2019-09-05 11:53:15.628 4009-4235/com.trap.terminal E/Media: onFrame faile
2019-09-05 11:53:15.628 4009-4235/com.trap.terminal W/System.err: java.lang.IllegalStateException
2019-09-05 11:53:15.628 4009-4235/com.trap.terminal W/System.err:     at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
2019-09-05 11:53:15.628 4009-4235/com.trap.terminal W/System.err:     at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2635)
2019-09-05 11:53:15.628 4009-4235/com.trap.terminal W/System.err:     at com.trap.terminal.media.Decoder.onFrame(Decoder.java:52)
2019-09-05 11:53:15.628 4009-4235/com.trap.terminal W/System.err:     at com.trap.terminal.VideoPlayThread.run(VideoPlayThread.java:46)
2019-09-05 11:53:15.628 4009-4235/com.trap.terminal E/Media: onFrame start
2019-09-05 11:53:15.628 4009-4235/com.trap.terminal E/Media: onFrame Thread:1991
2019-09-05 11:53:15.628 4009-4235/com.trap.terminal E/Media: onFrame faile`

**Comment by spianmo** [comment]
2019-09-05 11:53:14.659 4009-4258/com.trap.terminal D/AudioTrack: set(sessionID=0)
2019-09-05 11:53:14.659 4009-4258/com.trap.terminal D/AudioTrack: set(): streamType -1, sampleRate 44100, format 0x1, channelMask 0x1, frameCount 3536, flags #0, notificationFrames 0, sessionId 0, transferType 3, uid -1, pid -1
2019-09-05 11:53:14.661 4009-4261/com.trap.terminal I/OMXClient: IOmx service obtained
2019-09-05 11:53:14.667 4009-4259/com.trap.terminal D/SurfaceUtils: connecting to surface 0x7aabec0010, reason connectToSurface
2019-09-05 11:53:14.667 4009-4259/com.trap.terminal I/MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 4105218
2019-09-05 11:53:14.667 4009-4259/com.trap.terminal D/SurfaceUtils: disconnecting from surface 0x7aabec0010, reason connectToSurface(reconnect)
2019-09-05 11:53:14.667 4009-4259/com.trap.terminal D/SurfaceUtils: connecting to surface 0x7aabec0010, reason connectToSurface(reconnect)
2019-09-05 11:53:14.668 4009-4261/com.trap.terminal I/ExtendedACodec: setupVideoDecoder()
2019-09-05 11:53:14.668 4009-4261/com.trap.terminal I/ExtendedACodec: Decoder will be in frame by frame mode
2019-09-05 11:53:14.707 4009-4261/com.trap.terminal D/SurfaceUtils: set up nativeWindow 0x7aabec0010 for 1080x2340, color 0x7fa30c06, rotation 0, usage 0x20002900
2019-09-05 11:53:14.720 4009-4258/com.trap.terminal W/AudioTrack: Use of stream types is deprecated for operations other than volume control
2019-09-05 11:53:14.720 4009-4258/com.trap.terminal W/AudioTrack: See the documentation of AudioTrack() for what to use instead with android.media.AudioAttributes to qualify your playback use case
2019-09-05 11:53:14.726 4009-4265/com.trap.terminal I/OMXClient: IOmx service obtained
2019-09-05 11:53:14.727 4009-4265/com.trap.terminal W/ExtendedACodec: Failed to get extension for extradata parameter
2019-09-05 11:53:15.616 4009-4238/com.trap.terminal W/AudioTrack: releaseBuffer() track 0x7abee61c00 disabled due to previous underrun, restarting
2019-09-05 11:53:15.619 4009-4235/com.trap.terminal E/Media: onFrame start
2019-09-05 11:53:15.619 4009-4235/com.trap.terminal E/Media: onFrame Thread:1991
2019-09-05 11:53:15.619 4009-4235/com.trap.terminal E/Media: onFrame index:0
2019-09-05 11:53:15.619 4009-4244/com.trap.terminal E/ACodec: dequeueBuffer failed: NO_INIT(-19).
2019-09-05 11:53:15.620 4009-4235/com.trap.terminal E/Media: onFrame end
2019-09-05 11:53:15.620 4009-4235/com.trap.terminal E/Media: onFrame start
2019-09-05 11:53:15.620 4009-4235/com.trap.terminal E/Media: onFrame Thread:1991
2019-09-05 11:53:15.620 4009-4235/com.trap.terminal E/Media: onFrame index:1
2019-09-05 11:53:15.620 4009-4244/com.trap.terminal E/ACodec: dequeueBuffer failed: NO_INIT(-19).
2019-09-05 11:53:15.621 4009-4235/com.trap.terminal E/Media: onFrame end
2019-09-05 11:53:15.621 4009-4235/com.trap.terminal E/Media: onFrame start
2019-09-05 11:53:15.621 4009-4235/com.trap.terminal E/Media: onFrame Thread:1991
2019-09-05 11:53:15.621 4009-4235/com.trap.terminal E/Media: onFrame index:2
2019-09-05 11:53:15.621 4009-4244/com.trap.terminal E/ACodec: dequeueBuffer failed: NO_INIT(-19).
2019-09-05 11:53:15.621 4009-4235/com.trap.terminal E/Media: onFrame end
2019-09-05 11:53:15.621 4009-4235/com.trap.terminal E/Media: onFrame start
2019-09-05 11:53:15.621 4009-4235/com.trap.terminal E/Media: onFrame Thread:1991
2019-09-05 11:53:15.621 4009-4235/com.trap.terminal E/Media: onFrame index:3
2019-09-05 11:53:15.622 4009-4244/com.trap.terminal E/ACodec: dequeueBuffer failed: NO_INIT(-19).
2019-09-05 11:53:15.622 4009-4235/com.trap.terminal E/Media: onFrame end
2019-09-05 11:53:15.622 4009-4235/com.trap.terminal E/Media: onFrame start
2019-09-05 11:53:15.622 4009-4235/com.trap.terminal E/Media: onFrame Thread:1991
2019-09-05 11:53:15.622 4009-4235/com.trap.terminal E/Media: onFrame index:4
2019-09-05 11:53:15.622 4009-4244/com.trap.terminal E/ACodec: dequeueBuffer failed: NO_INIT(-19).
2019-09-05 11:53:15.622 4009-4235/com.trap.terminal E/Media: onFrame end
2019-09-05 11:53:15.623 4009-4235/com.trap.terminal E/Media: onFrame start
2019-09-05 11:53:15.623 4009-4235/com.trap.terminal E/Media: onFrame Thread:1991
2019-09-05 11:53:15.623 4009-4235/com.trap.terminal E/Media: onFrame index:5
2019-09-05 11:53:15.623 4009-4244/com.trap.terminal E/ACodec: dequeueBuffer failed: NO_INIT(-19).
2019-09-05 11:53:15.623 4009-4235/com.trap.terminal E/Media: onFrame end
2019-09-05 11:53:15.623 4009-4235/com.trap.terminal E/Media: onFrame start
2019-09-05 11:53:15.623 4009-4235/com.trap.terminal E/Media: onFrame Thread:1991
2019-09-05 11:53:15.626 4009-4244/com.trap.terminal W/SurfaceUtils: failed to get consumer usage bits. ignoring
2019-09-05 11:53:15.626 4009-4244/com.trap.terminal D/SurfaceUtils: set up nativeWindow 0x7aabb5d010 for 1088x2352, color 0x7fa30c06, rotation 0, usage 0x20002900
2019-09-05 11:53:15.626 4009-4244/com.trap.terminal E/ACodec: NATIVE_WINDOW_MIN_UNDEQUEUED_BUFFERS query failed: No such device (19)
2019-09-05 11:53:15.626 4009-4244/com.trap.terminal E/ACodec: Failed to allocate output port buffers after port reconfiguration: (-19)
2019-09-05 11:53:15.626 4009-4244/com.trap.terminal E/ACodec: signalError(omxError 0x80001001, internalError -19)
2019-09-05 11:53:15.626 4009-4244/com.trap.terminal E/ACodec: Error occurred while disabling the output port
2019-09-05 11:53:15.626 4009-4242/com.trap.terminal E/MediaCodec: Codec reported err 0xffffffed, actionCode 0, while in state 6
2019-09-05 11:53:15.627 4009-4235/com.trap.terminal E/Media: onFrame faile
2019-09-05 11:53:15.627 4009-4235/com.trap.terminal W/System.err: java.lang.IllegalStateException
2019-09-05 11:53:15.627 4009-4235/com.trap.terminal W/System.err:     at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
2019-09-05 11:53:15.627 4009-4235/com.trap.terminal W/System.err:     at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2635)
2019-09-05 11:53:15.627 4009-4235/com.trap.terminal W/System.err:     at com.trap.terminal.media.Decoder.onFrame(Decoder.java:52)
2019-09-05 11:53:15.627 4009-4235/com.trap.terminal W/System.err:     at com.trap.terminal.VideoPlayThread.run(VideoPlayThread.java:46)
2019-09-05 11:53:15.627 4009-4235/com.trap.terminal E/Media: onFrame start
2019-09-05 11:53:15.628 4009-4235/com.trap.terminal E/Media: onFrame Thread:1991
2019-09-05 11:53:15.628 4009-4242/com.trap.terminal D/SurfaceUtils: disconnecting from surface 0x7aabb5d010, reason disconnectFromSurface
2019-09-05 11:53:15.628 4009-4235/com.trap.terminal E/Media: onFrame faile
2019-09-05 11:53:15.628 4009-4235/com.trap.terminal W/System.err: java.lang.IllegalStateException
2019-09-05 11:53:15.628 4009-4235/com.trap.terminal W/System.err:     at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
2019-09-05 11:53:15.628 4009-4235/com.trap.terminal W/System.err:     at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2635)
2019-09-05 11:53:15.628 4009-4235/com.trap.terminal W/System.err:     at com.trap.terminal.media.Decoder.onFrame(Decoder.java:52)
2019-09-05 11:53:15.628 4009-4235/com.trap.terminal W/System.err:     at com.trap.terminal.VideoPlayThread.run(VideoPlayThread.java:46)
2019-09-05 11:53:15.628 4009-4235/com.trap.terminal E/Media: onFrame start
2019-09-05 11:53:15.628 4009-4235/com.trap.terminal E/Media: onFrame Thread:1991
2019-09-05 11:53:15.628 4009-4235/com.trap.terminal E/Media: onFrame faile

**Comment by spianmo** [comment]
一开始的log没格式化，看第二条

**Comment by spianmo** [comment]
已解决
